# Adres bazy danych (pobiera zmienn? z Dockera, a je?li nie ma, u?ywa domy?lnego localhost)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/task_manager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

# Automatyczna aktualizacja schematu bazy danych
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# Opcjonalne: Pokazywanie logów SQL
spring.jpa.show-sql=true